### ISSUE TITLE
Duplicate word "това"

### ISSUE THREAD

**Issue by atoponce** [assenv/diceware-wordlist-bg#1]
There is a duplicate word in the word list:

    % awk '{print $2}' /tmp/wordlist_utf_bg.asc | sort | uniq -c | sort -n | grep -P -v '^\s+1'
          2 това

It's located at indices 16412 and 62636:

    % grep -P '^[0-9]{5} това$' /tmp/wordlist_utf_bg.asc
    16412 това
    62636 това

**Comment by assenv** [comment]
thanks for the heads up, must have missed this somehow

**Comment by assenv** [comment]
fixed duplicate "това"

**Comment by atoponce** [comment]
Thanks!
